process.env.SITE = 'pix-site'
process.env.SITE_DOMAIN = 'pix.fr'
process.env.METABASE_API_URL = 'https://test.metabase.fr'
process.env.METABASE_USERNAME = 'username'
process.env.METABASE_PASSWORD = 'password'
process.env.DOMAIN_FR = 'example.fr'
process.env.DOMAIN_ORG = 'example.org'
