rewrite ^/en-gb(.*)$ /en$1 permanent;
rewrite ^/fr-be(.*)$ /fr-BE$1 permanent;
rewrite ^/nl-be(.*)$ /nl-BE$1 permanent;
rewrite ^/support/professionnel/faq-pro$ https://pro.pix.fr/support/professionnel/faq-pro redirect;
rewrite ^/employeurs$ https://pro.pix.fr redirect;
rewrite ^/conditions-generales-d-utilisation /pix-app-tos-2026-06-25 redirect;
rewrite ^/fr/conditions-generales-d-utilisation /fr/pix-app-tos-2026-06-25 redirect;
rewrite ^/fr-be/conditions-generales-d-utilisation /fr-be/pix-app-tos-2026-06-25 redirect;
rewrite ^/en/terms-and-conditions /en/pix-app-tos-2026-06-25 redirect;
rewrite ^/nl-be/algemene-gebruiksvoorwaarden /nl-be/pix-app-tos-2026-06-25 redirect;
