rewrite ^/en-gb(.*)$ /en$1 permanent;
rewrite ^/support/enseignement-superieur/etudiant-e$ https://support.pix.org redirect;
rewrite ^/support/professionnel/faq-pro$ https://pro.pix.fr/support/professionnel/faq-pro redirect;
rewrite ^/employeurs$ https://pro.pix.fr redirect;
rewrite ^/en/support/form/certification-center-support-contact https://pix.org/en/support-contact-form  redirect; 
rewrite ^/en/support/form/contact-pix-support https://pix.org/en/support-contact-form  redirect;
