---
version: 2.0

jobs:
  test:
    docker:
      - image: cimg/node:20.6.0
    steps:
      - checkout
      - run:
          working_directory: ./shared
          command: |
            cat package*.json > cachekey
      - restore_cache:
          working_directory: ./shared
          keys:
            - pix-site-shared-npm-{{ checksum "cachekey" }}
      - run:
          working_directory: ./shared
          command: |
            npm ci
      - save_cache:
          working_directory: ./shared
          key: pix-site-shared-npm-{{ checksum "cachekey" }}
          paths:
            - ~/.npm
      - run:
          working_directory: ./shared
          name: Test
          command: |
            npm run test

  e2e:
    docker:
      - image: mcr.microsoft.com/playwright:v1.38.1-focal
    resource_class: medium
    steps:
      - checkout

      - run:
          working_directory: ./pix-site
          environment:
            SITE: pix-site
          command: |
              npm ci

      - run:
          working_directory: ./pix-site
          command: |
            npm run test:e2e:install

      - run:
          working_directory: ./pix-site
          name: Run E2E tests
          environment:
            SITE: pix-site
            PLAYWRIGHT_JUNIT_OUTPUT_NAME: test-results/e2e-junit-results.xml
          command: npm run test:e2e:ci -- --reporter=junit
      - store_test_results:
          path: test-results/

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - e2e
