---
version: 2.1

executors:
  node-docker:
    parameters:
      node-version:
        # renovate datasource=node-version depName=node
        default: 20.17.0
        type: string
    docker:
      - image: cimg/node:<<parameters.node-version>>
    resource_class: small
  playwright:
    docker:
      - image: mcr.microsoft.com/playwright:v1.38.1-focal
    resource_class: medium+

jobs:
  checkout:
    executor:
      name: node-docker
    working_directory: ~/pix-site
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/pix-site
          paths:
            - .


  lint:
    executor:
      name: node-docker
    working_directory: ~/pix-site
    steps:
      - attach_workspace:
          at: ~/pix-site
      - run: cat package*.json > cachekey
      - restore_cache:
          keys:
            - v1-pix-site-lint-npm-{{ checksum "cachekey" }}
      - run:
          name: Install dependencies
          command: |
            npm ci
      - save_cache:
          key: v1-pix-site-lint-npm-{{ checksum "cachekey" }}
          paths:
            - ~/.npm
      - run:
          name: Lint
          command: |
            npm run lint


  test-shared:
    executor:
      name: node-docker
    working_directory: ~/pix-site/shared
    steps:
      - attach_workspace:
          at: ~/pix-site
      - run: cat package*.json > cachekey
      - restore_cache:
          keys:
            - v1-pix-site-shared-npm-{{ checksum "cachekey" }}
      - run:
          name: Install dependencies
          command: |
            npm ci
      - save_cache:
          key: v1-pix-site-shared-npm-{{ checksum "cachekey" }}
          paths:
            - ~/.npm
      - run:
          name: Test
          environment:
            DOMAIN_FR: 'https://example.fr'
            DOMAIN_ORG: 'https://example.org'
          command: |
            npm test

  test-pix-site:
    executor:
      name: node-docker
    working_directory: ~/pix-site/pix-site
    steps:
      - attach_workspace:
          at: ~/pix-site
      - run: cat package*.json > cachekey
      - restore_cache:
          keys:
            - v1-pix-site-pix-site-npm-{{ checksum "cachekey" }}
      - run:
          name: Install dependencies
          command: |
            npm ci
      - save_cache:
          key: v1-pix-site-pix-site-npm-{{ checksum "cachekey" }}
          paths:
            - ~/.npm
      - run:
          name: Test
          environment:
            SITE: pix-site
            SITE_DOMAIN: 'ORG'
            DOMAIN_FR: 'https://example.fr'
            DOMAIN_ORG: 'https://example.org'
          command: |
            npm test

  e2e-pix-site:
    executor:
      name: playwright
    working_directory: ~/pix-site/pix-site
    steps:
      - attach_workspace:
          at: ~/pix-site
      - run: cat package*.json > cachekey
      - restore_cache:
          keys:
            - v2-pix-site-e2e-pix-site-npm-{{ checksum "cachekey" }}
      - run:
          name: Install dependencies
          environment:
            SITE: pix-site
          command: |
            npm ci
      - save_cache:
          key: v2-pix-site-e2e-pix-site-npm-{{ checksum "cachekey" }}
          paths:
            - ~/.npm
            - ~/.cache/ms-playwright

      - run:
          name: Install E2E dependencies
          command: |
            npm run test:e2e:install

      - run:
          name: Run E2E tests
          environment:
            SITE: pix-site
            PLAYWRIGHT_JUNIT_OUTPUT_NAME: test-results/e2e-junit-results.xml
          command: npm run test:e2e:ci -- --reporter=junit
      - store_test_results:
          path: test-results/

workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout:
          context: pix-site

      - lint:
          context: pix-site
          requires:
            - checkout

      - test-shared:
          context: pix-site
          requires:
            - checkout

      - test-pix-site:
          context: pix-site
          requires:
            - checkout

      - e2e-pix-site:
          context: pix-site
          requires:
            - checkout
