version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: production_nginx
    tmpfs:
      - /etc/nginx/logs
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./build:/app/build
    ports:
      - 80:80