name: automerge check

on:
  pull_request:
    types:
      - labeled
  check_suite:
    types:
      - completed

jobs:
  automerge:
    if: >
      ${{ contains(github.event.pull_request.labels.*.name, ':rocket: Ready to Merge') }}
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.14.3"
        env:
          GITHUB_TOKEN: "${{ github.token }}"
          MERGE_LABELS: ":rocket: Ready to Merge"
          MERGE_COMMIT_MESSAGE: "pull-request-title"
          UPDATE_LABELS: ":rocket: Ready to Merge"
          UPDATE_METHOD: "rebase"
          MERGE_FORKS: "false"
